### ISSUE TITLE
[FEATURE] Needs English translation

### ISSUE THREAD

**Issue by Virinas-code** [Group-of-PLAGUE-Time-Wanderer/PLAGUE-Time-Wanderer#7]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like having an English translation of the README

**Describe alternatives you've considered**
Make two repositories : No.

**Comment by tt-thoma** [comment]
Do it

**Comment by Virinas-code** [comment]
OK !

**Comment by tt-thoma** [comment]
Noice
